apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: a11ywatch-backend
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: a11ywatch/a11ywatch:latest
          ports:
            - containerPort: 3280
