apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: a11ywatch-backend
spec:
  template:
    spec:
      containers:
        - image: a11ywatch/a11ywatch:latest
          ports:
            - containerPort: 3280
        #   env:
        #     - name: REDIS_CLIENT
        #       value: redis://redis:6379,password=${{ secrets.REDISPASSWORD }}
        #     - name: REDIS_HOST
        #       value: redis
      #  - image: bitnami/redis:6.0
      #    env:
      #      - name: REDIS_MASTER_PASSWORD
      #        value: ${{ secrets.REDISPASSWORD }}
