apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: a11ywatch-backend
spec:
  template:
    spec:
      containers:
        - image: a11ywatch/core:latest
          ports:
            - containerPort: 3280
          env:
            - name: REDIS_CLIENT
              value: redis://redis:6379
            - name: REDIS_HOST
              value: redis
        - image: bitnami/redis:6.0
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: yes
