<<<<<<< HEAD
name: Sync BigQuery to CSV
=======
name: Sync BigQuery and CSV
>>>>>>> a707dc1b75abf1f08f56b2280b619ac3e4435145
on:
  schedule:
    - cron: "5 1/6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud
<<<<<<< HEAD
        uses: google-github-actions/auth@v1
=======
        uses: google-actions/setup-gcloud@latest
>>>>>>> a707dc1b75abf1f08f56b2280b619ac3e4435145
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_KEY }}
      - name: Export BigQuery table to CSV
        run: |
          gcloud auth activate-service-account --key-file=${GOOGLE_CLOUD_KEY}
          bq --quiet --project_id=${PROJECT_ID} extract --destination_format=CSV ${DATASET}.${TABLE} ${CSV_PATH}
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ${CSV_PATH}
          git commit -m "Sync with BigQuery table"
          git push
