# Syncs CSV file at data/domains/domains.csv to BigQuery Table
#
#
#
#
name: Push CSV to BigQuery
on:
  push:
    paths:
      - "data/domains/domains.csv"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
      - name: Load CSV to BigQuery
        run: |
          gcloud auth activate-service-account --key-file=${GCR_KEY}
          bq --quiet --project_id=${PROJECT_ID} load --source_format=CSV ${DATASET}.${TABLE} ${CSV_PATH}
