# Syncs CSV file at data/domains/domains.csv to BigQuery Table
#
# GCloud Docs:
#         - https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account
#         - https://github.com/google-github-actions/auth
#         - https://github.com/google-github-actions/auth
#
#           - GCloud CLI | BigQuery Reference
#           - https://cloud.google.com/bigquery/docs/reference/bq-cli-reference
#
#
name: Push CSV to BigQuery
on:
  push:
    paths:
      - "data/domains/domains.csv"
  workflow_dispatch:

jobs:
  sync:
    name: Upload CSV to BigQuery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: "auth"
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
        #  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: Load CSV to BigQuery
        run: |
          gcloud auth activate-service-account ${{ secrets.GOOGLE_SERVICE_ACCOUNT }} --key-file=${{ steps.auth.outputs.credentials_file_path }}
          bq load --source_format=CSV ${{ vars.PROJECT_ID }}:${{ vars.DATASET }}.${{ vars.TABLE }} ${{ vars.CSV_PATH }}
