name: Libraries.io

on: [push, pull_request]

jobs:
  librariesio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1

      - name: Get Dependencies
        run: |
          npm install libraries.io-client
          node -e "const lib = require('libraries.io-client'); console.log(lib.getDependencies('npm', '<package-name>'));" > dependencies.json

      - name: Create or Update CSV
        run: |
          echo "repoName,dependency,LinkToDependency,DepencyRepoLicense" > ./data/deps.csv
          jq -r '.dependencies[] | [.name, .version, .homepage_url, .licenses[0].name] | @csv' dependencies.json >> ./data/deps.csv
