#  Based on Publishing and installing a package with GitHub Actions
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
#
name: Build & Deploy A11yWatch
on:
  push:
    branches:
      - dev
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-web:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout a11ywatch web repository
        uses: actions/checkout@v3
        with:
          repository: a11ywatch/web
          ref: 22bcd78ba5df25f40cbf99e5e8bd8c3b790674fb

      - name: TODO temporarily patch Dockerfile, remove when https://github.com/a11ywatch/web/pull/98 in stable commit.
        run: curl -so Dockerfile https://raw.githubusercontent.com/grugnog/web/build-args/Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API=https://a11ywatch-backend.public-sector-a11y.app.civicactions.net/graphql
            WEB_SOCKET_URL=ws://a11ywatch-backend.public-sector-a11y.app.civicactions.net/graphql

  deploy:
    name: Deploy to Namespace
    needs: build-web
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - name: Deploy
        run: kubectl apply --namespace=public-sector-a11y -f k8s
